#ifndef CONFIGURATIONS_H_
#define CONFIGURATIONS_H_

/* Macros */
#define NUMBER_OF_INSTRUCTIONS	27
#define NUMBER_OF_ALLOC_INSTRUCTIONS	6
#define MAX_FILE_NAME_SIZE	20
#define MAX_LABEL_SIZE	18
#define MAX_VAR_NAME	10
#define MAX_LINE_SIZE 80
#define MAX_LABEL_CALL 10

#endif

